POST http://localhost:3333/videos
Content-Type: application/json

{
  "title": "Vídeo node",
  "description": "Primeiro vídeo",
  "duration": 180
}

### 

GET http://localhost:3333/videos?search=node

###

PUT http://localhost:3333/videos/0e48c4bc-76c3-4730-9ccc-f6650b2ec8f8
Content-Type: application/json

{
  "title": "Vídeo 02",
  "description": "Primeiro vídeo",
  "duration": 180
}

### 
DELETE http://localhost:3333/videos/94005017-4dd5-4928-9cf7-dc6635ef15b5