POST http://localhost:3333/videos
Content-Type: application/json

{
  "title": "Vídeo node",
  "description": "Primeiro vídeo",
  "duration": 180
}

### 

GET http://localhost:3333/videos

###

PUT http://localhost:3333/videos/3fe31317-9f4c-4a0b-a07a-58557a8ed2c7
Content-Type: application/json

{
  "title": "Vídeo 02",
  "description": "Vídeo 2",
  "duration": 180
}

### 
DELETE http://localhost:3333/videos/3fe31317-9f4c-4a0b-a07a-58557a8ed2c7